# vocabulary data for the NER keyword extraction pipeline
# STOPWORDS/ KNOWN NAME MAPPINGS ARE STILL BEING ADDED


# look through if anything needs to be fixed or added!


# all entries must be lowercase the check does clean.lower() in STOPWORDS
STOPWORDS = {
    # prediction market boilerplate
    "yes", "no", "will", "market", "polymarket", "resolve", "resolves",
    "before", "after", "end", "start", "date", "price", "week", "month",
    "year", "day", "time",


    # months 
    "january", "february", "march", "april", "may", "june",
    "july", "august", "september", "october", "november", "december",
    "jan", "feb", "mar", "apr", "jun", "jul", "aug", "sep", "oct", "nov", "dec",
    "q1", "q2", "q3", "q4", "2022", "2023", "2024", "2025", "2026",
    "first", "second", "third", "fourth", "new", "old",

    # titles and roles
    "prime", "minister", "president", "secretary", "general", "leader",
    "chief", "chairman", "director", "ambassador", "senator", "governor", "supreme",
    # noise that leaks through as proper nouns
    "et", "next", "hell", "hottest", "god", "wars", "div",
    "ass", "brutal", "brutally", "beautiful", "deadlock", "dictator",
    "globalist", "globalism", "suit", "pond", "roof", "egg",
    "trillion", "victory", "edition", "phase", "borders", "powers",
    "slander", "natural", "million", "emergency", "response", "rooms",
    "people", "power", "world", "climate", "economic", "development",
    "military", "human", "shield", "proxy", "war", "oblast",
    "da", "diy", "onseptember", "clock", "pay", "pm", "country",

    "nord", "stream",  # once consumed fix is in, these shouldn't appear but belt-and-braces
    "iron", "dome", "suez", "canal", "hostage", "aircraft", "farmer", "heritage",
    "joe",   "steve", "marco", "javier", "recep", "tayyip", # fragments of already-handled names
    "luiz", "inácio", "silva",  # Lula fragments  # once consumed fix is in, these shouldn't appear but belt-and-braces
    "suez", "canal", "chancellor", "sovereign", "sovereignty",
    "artificial", "intelligence",  # caught by phrase lookup as "AI" instead
    "reza", "pahlavi",             # caught by phrase lookup
    "médecins", "sans", "frontières",
    "pavel", 
}

# maps lowercase token/phrase  canonical display form
# two purposes:
# pass 1 normalisation - collapses "Benjamin Netanyahu" -> "Netanyahu" etc.
# pass 3 fallback - catches names spaCy doesn't recognise at all
# all keys must be lowercase

KNOWN_NAMES = {
    # people 
    # zelensky
    "zelenskyy":                        "Zelenskyy",
    "zelensky":                         "Zelenskyy",
    "volodymyr zelenskyy":              "Zelenskyy",
    "volodymyr zelensky":               "Zelenskyy",
    "volodymyr":                        "Zelenskyy",

    # netanyahu
    "netanyahu":                        "Netanyahu",
    "benjamin netanyahu":               "Netanyahu",
    "benjamin":                         "Netanyahu",

    # putin
    "putin":                            "Putin",
    "vladimir putin":                   "Putin",

    # trump
    "trump":                            "Trump",
    "donald trump":                     "Trump",

    # xi jinping
    "xi jinping":                       "Xi Jinping",
    "jinping":                          "Xi Jinping",
    "xi":                               "Xi Jinping",

    # macron
    "macron":                           "Macron",
    "emmanuel macron":                  "Macron",

    # erdogan
    "erdogan":                          "Erdoğan",
    "erdoğan":                          "Erdoğan",
    "recep tayyip erdoğan":             "Erdoğan",
    "recep tayyip erdogan":             "Erdoğan",

    # modi
    "modi":                             "Modi",
    "narendra modi":                    "Modi",

    # assad
    "assad":                            "Assad",
    "bashar al-assad":                  "Assad",

    # yoon
    "yoon":                             "Yoon",
    "yoon suk yeol":                    "Yoon",

    # lukashenko
    "lukashenko":                       "Lukashenko",
    "aleksandr lukashenko":             "Lukashenko",

    # khamenei
    "khamenei":                         "Khamenei",
    "ali khamenei":                     "Khamenei",
    "ayatollah khamenei":               "Khamenei",

    # maduro
    "maduro":                           "Maduro",
    "nicolás maduro":                   "Maduro",

    # milei
    "milei":                            "Milei",
    "javier milei":                     "Milei",

    # lula
    "lula":                             "Lula",
    "luiz inácio lula da silva":        "Lula",
    "luiz inácio lula da silva":        "Lula",
    "lula da silva":                    "Lula",

    # bolsonaro
    "bolsonaro":                        "Bolsonaro",
    "jair bolsonaro":                   "Bolsonaro",

    # starmer
    "starmer":                          "Starmer",
    "keir starmer":                     "Starmer",
    "keir":                             "Starmer",

    # orban
    "orban":                            "Orbán",
    "orbán":                            "Orbán",
    "viktor orbán":                     "Orbán",
    "viktor orban":                     "Orbán",

    # sisi
    "sissi":                            "Sisi",
    "abdel fattah el-sisi":             "Sisi",
    "abdel fattah el sisi":             "Sisi",

    # mbs
    "mbs":                              "MBS",
    "mohammed bin salman":              "MBS",
    "crown prince mohammed bin salman": "MBS",

    # nasrallah
    "nasrallah":                        "Nasrallah",
    "hassan nasrallah":                 "Nasrallah",

    # scholz
    "scholz":                           "Scholz",
    "olaf scholz":                      "Scholz",

    # merz
    "merz":                             "Merz",
    "friedrich merz":                   "Merz",

    # meloni
    "meloni":                           "Meloni",
    "giorgia meloni":                   "Meloni",

    # vance
    "vance":                            "Vance",
    "jd vance":                         "Vance",

    # witkoff
    "witkoff":                          "Witkoff",

    # rutte
    "rutte":                            "Rutte",
    "mark rutte":                       "Rutte",

    # al-sharaa
    "al-sharaa":                        "Al-Sharaa",
    "ahmed al-sharaa":                  "Al-Sharaa",
    "ahmed al shara":                   "Al-Sharaa",

    # elon musk
    "elon":                             "Elon Musk",
    "elon musk":                        "Elon Musk",
    "musk":                             "Elon Musk",

    # von der leyen
    "ursula von der leyen":             "Von der Leyen",
    "ursula":                           "Von der Leyen",
    "leyen":                            "Von der Leyen",
    "ursula von der":           "Von der Leyen",

    # pope
    "pope":                             "Pope",
    "pope leo":                         "Pope",
    "pope leo xiv":                     "Pope",
    "leo xiv":                          "Pope",
    "pope francis":                     "Pope Francis",

    # epstein
    "epstein":                          "Epstein",

    # carney
    "carney":                           "Carney",
    "mark carney":                      "Carney",

    # people missing
    "kim jong un":              "Kim Jong Un",
    "kim":                      "Kim Jong Un",   # careful, ambiguous
    "jerome powell":            "Jerome Powell",
    "powell":                   "Jerome Powell",
    "marco rubio":              "Marco Rubio",
    "rubio":                    "Marco Rubio",
    "greta thunberg":           "Greta Thunberg",
    "greta thunberg's":         "Greta Thunberg",
    "trudeau":                  "Trudeau",
    "justin trudeau":           "Trudeau",
    "obama":                    "Obama",
    "shigeru ishiba":           "Ishiba",
    "ishiba":                   "Ishiba",
    "pedro sánchez":            "Sánchez",
    "guterres":                 "Guterres",
    "antónio guterres":         "Guterres",
    "lai ching-te":             "Lai Ching-te",
    "pablo durov":              "Durov",
    "durov":                    "Durov",
    "pablo durov":               "Durov",
    "pavel durov":               "Durov",
    "pavel":                    "Durov",

    "mrbeast":                  "MrBeast",
    "sinwar":                   "Sinwar",
    "yahya sinwar":             "Sinwar",
    "ben gvir":                 "Ben Gvir",
    "reza pahlavi":             "Reza Pahlavi",

    "giorgia":                      "Meloni",     # showing solo
    "javier":                       "Milei",      # or just stopword it
    "marco":                        "Marco Rubio",



    # groups / factions
    "houthi":                           "Houthi",
    "houthis":                          "Houthi",
    "wagner":                           "Wagner",
    "idf":                              "IDF",
    "unrwa":                            "UNRWA",
    "hts":                              "HTS",
    "pkk":                              "PKK",
    "brics":                            "BRICS",

    #  country/bloc codes 
    "us":                               "USA",
    "u.s":                              "USA",
    "u.s.":                             "USA",
    "u.s.a":                            "USA",
    "usa":                              "USA",
    "united states":                    "USA",
    "uk":                               "UK",
    "united kingdom":                   "UK",
    "eu":                               "EU",
    "european union":                   "EU",
    "\"european union":                 "EU",
    "the european union":               "EU",
    "uae":                              "UAE",
    "nato":                             "NATO",
    "ukraini":                        "Ukraine",

    # demonyms → country
    "iranian":                          "Iran",
    "israeli":                          "Israel",
    "israel's":                         "Israel",
    "russian":                          "Russia",
    "syrian":                           "Syria",
    "turkish":                          "Turkey",
    "türkiye":                          "Turkey",
    "armenian":                         "Armenia",
    "lebanese":                         "Lebanon",
    "chinese":                          "China",
    "indian":                           "India",
    "south korean":                     "South Korea",
    "north korean":                     "North Korea",
    "polish":                           "Poland",
    "gazan":                            "Gaza",
    "gazans":                           "Gaza",
    "crimean":                          "Crimea",
    "saudi":                            "Saudi Arabia",

    # places spaCy misses
    "baghdad":                          "Baghdad",
    "tehran":                           "Tehran",
    "heathrow":                         "Heathrow",
    "fordow":                           "Fordow",
    "baglihar":                         "Baglihar",
    "kharg":                            "Kharg",
    "hormuz":                           "Hormuz",
    "crimea":                           "Crimea",
    "donbas":                           "Donbas",
    "donbass":                          "Donbas",
    "zaporizhzhia":                     "Zaporizhzhia",
    "mariupol":                         "Mariupol",
    "kharkiv":                          "Kharkiv",
    "pokrovsk":                         "Pokrovsk",
    "sudzha":                           "Sudzha",
    "siversk":                          "Siversk",
    "panama":                           "Panama",
    "venezuelan":                       "Venezuela",
    "pakistani":                        "Pakistan",
    "afghan":                           "Afghanistan",

    "damascus":                     "Damascus",
    "kyiv":                         "Kyiv",
    "donetsk":                      "Donetsk",
    "persian gulf":                 "Persian Gulf",
    "iron dome":                    "Iron Dome",        # already there
    "gulf leaders summit":          "Gulf Leaders Summit",
    "nato public forum address":    "NATO Public Forum Address",
    "constitutional court":         "Constitutional Court",

    "lukashenko":                   "Lukashenko",       # already there, confirm spelling
    "maduro":                       "Maduro",           # already there
    "carney":                       "Carney", 

    # compound place names 
    "iron dome":                        "Iron Dome",
    "nord stream":                      "Nord Stream",
    "suez canal":                       "Suez Canal",
    "black sea":                        "Black Sea",
    "persian gulf":                     "Persian Gulf",
    "south korea":                      "South Korea",
    "north korea":                      "North Korea",
    "saudi arabia":                     "Saudi Arabia",

    "artificial intelligence":  "AI",
    "a.i":                          "AI",
    "a.i.":                         "AI",          
    "hezbollah ceasefire":      "Hezbollah",
    "ukraine ceasefire":        "Ukraine",
    "abraham accord":           "Abraham Accord",
    "warsaw pact":              "Warsaw Pact",
    "west bank":                "West Bank",
    "the west bank":            "West Bank",
    "the white house":          "White House",
    "white house":                  "White House",
    "the house of councillors": "House of Councillors",
    "the un general assembly":  "UN General Assembly",
    "un general assembly":      "UN General Assembly",

    # orgs/groups missing
    "doge":                     "DOGE",
    "icc":                      "ICC",
    "who":                      "WHO",           # careful - spaCy will grab "who" as pronoun a lot
    "wto":                      "WTO",
    "g7":                       "G7",
    "spacex":                   "SpaceX",
    "deepseek":                 "DeepSeek",
    "tesla":                    "Tesla",
    "tiktok":                   "TikTok",
    "xai":                      "xAI",
}







# ALL_TOPICS
# master list of all ProQuest corpora
# must match folder names exactly under data/raw/proquest/
# drives both TOPICS (parse + score) and AVAILABLE_CORPORA (collect)
# keep it alphabetical incase we want to add extra so its easy to see


ALL_TOPICS = [
    "armenia_trump",
    "bolsonaro",
    "cambodia_thialand",
    "ceasefire_russia_ukraine",
    "china_taiwan",
    "crimea",
    "elon_musk_trump",
    "gaza_israel",
    "gaza_usa",
    "germany_trump",
    "gulf_trump",
    "greenland",
    "hamas_israel",
    "hezbollah_israel",
    "hezbollah_nasrallah",
    "houthi",
    "india_pakistan",
    "iran_israel",
    "iran_trump",
    "iran_usa",
    "iraq_israel",
    "israel_lebanon",
    "israel_saudi",
    "israel_syria",
    "israel_trump",
    "israel_yemen",
    "japan_election",
    "jerome_powell",
    "khamenei",
    "kupiansk_russia",
    "lukashenko",
    "lula",
    "machado",
    "macron_trump",
    "mbs",
    "meloni",
    "milei",
    "merz_trump",
    "moscow_ukraine",
    "nato_rutte",
    "netanyahu",
    "netanyahu_unga",
    "north_korea",
    "poland_trump", 
    "pokrovsk_russia",
    "pope",
    "putin",
    "putin_zelenskyy",
    "russia_siversk",
    "russia_sudzha",
    "russia_syria",
    "russia_ukraine",
    "saudi_arabia_usa",
    "south_african_trump",
    "south_korea_trump",
    "starmer_trump",
    "syria",
    "trump_putin",
    "trump_turkey",
    "trump_un_general_assembly",
    "trump_zelenskyy",
    "usa_venezuela",
    "xi_jinping",
    "yoon",
    "zelenskyy",
    "alaska",
    "carney_trump",
    "orban",
    "panama_trump",
    "spain_sanchez",
    "switzerland_trump",
    "greta_thunberg"
]
 
# used by parse_proquest.py and finbert_scorer.py
TOPICS = ALL_TOPICS
 
# used by collect_ft.py
AVAILABLE_CORPORA = set(ALL_TOPICS)



#  4. KEYWORD_TO_CORPORA 
# maps NER keyword → list of corpora containing relevant articles
# keys must match canonical display form from KNOWN_NAMES above
 
KEYWORD_TO_CORPORA = {

    # ── Israel / Palestine ────────────────────────────────────────────────────
    "Israel":        ["gaza_israel", "hamas_israel", "israel_lebanon",
                      "israel_syria", "israel_yemen", "israel_saudi",
                      "netanyahu_unga", "hezbollah_israel", "iraq_israel",
                      "israel_trump", "netanyahu", "iran_israel"],
    "Trump":         ["iran_trump", "gaza_usa", "saudi_arabia_usa", "usa_venezuela",
                      "trump_zelenskyy", "trump_putin", "elon_musk_trump",
                      "germany_trump", "macron_trump", "merz_trump",
                      "south_african_trump", "south_korea_trump",
                      "starmer_trump", "trump_turkey", "trump_un_general_assembly",
                      "israel_trump", "iran_trump", "gulf_trump","panama_trump", "switzerland_trump", "carney_trump",
                      "armenia_trump", "nato_rutte", "poland_trump"],
    "Iran":          ["iran_israel", "iran_usa", "iran_trump", "khamenei"],
    "USA":           ["iran_usa", "gaza_usa", "saudi_arabia_usa",
                      "usa_venezuela", "trump_zelenskyy", "trump_putin"],
    "Russia":        ["russia_ukraine", "moscow_ukraine", "russia_syria",
                      "ceasefire_russia_ukraine", "russia_siversk", "russia_sudzha",
                      "trump_putin", "putin_zelenskyy",
                      "kupiansk_russia", "pokrovsk_russia", "zelenskyy", "crimea"],
    "Zelenskyy":     ["zelenskyy", "trump_zelenskyy", "putin_zelenskyy",
                      "russia_ukraine", "ceasefire_russia_ukraine", "crimea"],
    "Ukraine":       ["russia_ukraine", "moscow_ukraine", "trump_zelenskyy",
                      "ceasefire_russia_ukraine", "putin_zelenskyy",
                      "russia_siversk", "russia_sudzha", "zelenskyy", "crimea"],
    "Yemen":         ["israel_yemen", "houthi"],
    "Putin":         ["trump_putin", "putin_zelenskyy", "russia_ukraine", "putin"],
    "Gaza":          ["gaza_israel", "gaza_usa", "hamas_israel"],
    "Netanyahu":     ["netanyahu_unga", "hamas_israel", "netanyahu", "israel_trump"],
    "Syria":         ["israel_syria", "russia_syria", "syria"],
    "Hamas":         ["hamas_israel", "gaza_israel"],
    "South Korea":   ["south_korea_trump", "yoon"],
    "India":         ["india_pakistan"],
    "NATO":          ["nato_rutte"],
    "UN General Assembly": ["trump_un_general_assembly", "netanyahu_unga"],
    "Pakistan":      ["india_pakistan"],
    "Starmer":       ["starmer_trump"],
    "Turkey":        ["trump_turkey"],
    "Elon Musk":     ["elon_musk_trump"],
    "North Korea":   ["north_korea"],
    "Japan":         ["japan_election"],
    "Saudi Arabia":  ["israel_saudi", "saudi_arabia_usa", "gulf_trump", "mbs"],
    "China":         ["china_taiwan", "xi_jinping"],
    "Pope":          ["pope"],
    "Houthi":        ["israel_yemen", "houthi"],
    "Merz":          ["merz_trump", "germany_trump"],
    "House of Councillors": ["japan_election"],
    "Poland":        ["poland_trump"],
    "Xi Jinping":    ["china_taiwan", "xi_jinping"],
    "UK":            ["starmer_trump"],
    "Macron":        ["macron_trump"],
    "Bitcoin":       [],
    "Yoon":          ["yoon", "south_korea_trump"],
    "Lebanon":       ["israel_lebanon", "hezbollah_nasrallah", "hezbollah_israel"],
    "Crypto":        [],
    "UN":            ["trump_un_general_assembly", "netanyahu_unga"],
    "EU":            [],
    "Gulf Leaders Summit": ["gulf_trump"],
    "Vance":         ["trump_zelenskyy", "trump_putin"],
    "Rutte":         ["nato_rutte"],
    "NATO Public Forum Address": ["nato_rutte"],
    "Palestine":     ["gaza_israel", "hamas_israel", "gaza_usa"],
    "South African": ["south_african_trump"],
    "Khamenei":      ["khamenei", "iran_israel", "iran_usa"],
    "Armenia":       ["armenia_trump"],
    "Al-Sharaa":     ["syria"],
    "Pokrovsk":      ["pokrovsk_russia", "russia_ukraine"],
    "Qatar":         ["gaza_israel", "hamas_israel"],
    "AI":            [],
    "France":        ["macron_trump"],
    "Hezbollah":     ["hezbollah_nasrallah", "israel_lebanon", "hezbollah_israel"],
    "Kim Jong Un":   ["north_korea"],
    "Venezuela":     ["usa_venezuela"],
    "Canada":        ["carney_trump"],
    "Moscow":        ["moscow_ukraine", "russia_ukraine"],
    "Germany":       ["germany_trump", "merz_trump"],
    "Lula":          ["lula"],
    "MBS":           ["mbs", "israel_saudi", "saudi_arabia_usa", "gulf_trump"],
    "Crimea":        ["crimea", "russia_ukraine", "ceasefire_russia_ukraine"],
    "Brazil":        [],
    "Bolsonaro":     ["bolsonaro"],
    "Egypt":         ["gaza_israel", "gaza_usa"],
    "Greta Thunberg": ["greta_thunberg"],
    "Constitutional Court": ["yoon", "south_korea_trump"],
    "Siversk":       ["russia_siversk"],
    "Biden":         [],
    "Erdoğan":       ["trump_turkey"],
    "Iraq":          ["iraq_israel"],
    "Baier":         [],
    "Maduro":        ["usa_venezuela"],
    "Damascus":      ["israel_syria", "syria"],
    "Taiwan":        ["china_taiwan"],
    "Sudzha":        ["russia_sudzha"],
    "Kupiansk":      ["kupiansk_russia"],
    "Yunakivka":     ["russia_ukraine"],          # frontline village, best coverage is general russia_ukraine
    "Thailand":      ["cambodia_thialand"],
    "Jerome Powell": ["jerome_powell"],
    "Assad":         ["israel_syria", "russia_syria", "syria"],
    "Rodynske":      ["russia_ukraine"],
    "Donbas":        ["russia_ukraine", "ceasefire_russia_ukraine"],
    "Milei":         ["milei"],
    "Belarus":       ["lukashenko"],
    "Switzerland":   ["switzerland_trump"],
    "Mexico":        [],
    "Apple":         [],
    "Fordow":        ["iran_israel", "iran_usa"],
    "Australia":     [],
    "Argentina":     ["milei"],
    "Novopavlivka":  ["russia_ukraine"],
    "Von der Leyen": [],
    "TikTok":        [],
    "Dnipropetrovsk": ["russia_ukraine"],
    "Beirut Embassy": ["israel_lebanon", "hezbollah_nasrallah"],
    "Meloni":        ["meloni"],
    "Cambodia":      ["cambodia_thialand"],
    "Dobropillia":   ["russia_ukraine"],
    "Jordan":        ["gaza_israel"],
    "MrBeast":       [],
    "Greenland":     ["greenland"],
    "Italy":         ["meloni"],
    "UAE":           ["gulf_trump", "israel_saudi"],
    "Saudi-US":      ["saudi_arabia_usa", "gulf_trump"],
    "Congress":      ["iran_usa", "gaza_usa"],
    "Nord Stream":   ["russia_ukraine"],
    "Afghanistan":   [],
    "Nasrallah":     ["hezbollah_nasrallah", "israel_lebanon"],
    "Alaska":        ["alaska"],
    "Carney":         ["carney_trump"],
    "Udachne":       ["russia_ukraine"],
    "Pope Francis":  ["pope"],
    "Lukashenko":    ["lukashenko"],
    "Thailand x Cambodia": ["cambodia_thialand"],
    "Handala":       ["gaza_israel", "hamas_israel"],
    "Hungary":       ["orban"],
    "Ceasefire":     ["ceasefire_russia_ukraine", "russia_ukraine"],
    "Spain":         ["spain_sanchez"],
    "Modi":          ["india_pakistan"],
    "Dimonah":       ["iran_israel"],
    "JCP":           ["japan_election"],
    "Reiwa Shinsengumi": ["japan_election"],
    "Suez Canal":    [],
    "Tesla":         ["elon_musk_trump"],
    "Reza Pahlavi":  ["iran_israel", "iran_usa"],
    "Austria":       [],
    "Vatican":       ["pope"],
    "Sinwar":        ["hamas_israel", "gaza_israel"],
    "Panama":        ["panama_trump"],
    "Black Sea":     ["russia_ukraine"],
    "Machado":       ["machado", "usa_venezuela"],
    "Witkoff":       ["trump_zelenskyy", "trump_putin"],
    "West Bank":     ["gaza_israel", "hamas_israel"],
    "Indonesia":     [],
    "Stepanivka":    ["russia_ukraine"],
    "UNRWA":         ["gaza_israel", "gaza_usa"],
    "DeepSeek":      [],
    "Lai Ching-te":  ["china_taiwan"],
    "NPT":           ["iran_usa", "iran_israel", "north_korea"],
    "Gulf State":    ["gulf_trump", "saudi_arabia_usa"],
    "White House":   ["trump_zelenskyy", "trump_putin"],
    "IDF":           ["gaza_israel", "hamas_israel"],
    "CDP":           [],
    "Suwayda":       ["syria"],
    "Marco Rubio":   ["trump_zelenskyy", "trump_putin", "iran_trump"],
    "Beirut":        ["israel_lebanon", "hezbollah_nasrallah"],
    "Telegram":      [],
    "Iran Nuke":     ["iran_israel", "iran_usa", "iran_trump"],
    "Philippines":   [],
    "JIP":           ["japan_election"],
    "Komeito":       ["japan_election"],
    "DPP":           ["china_taiwan"],
    "Mintsuku":      ["japan_election"],
    "Finland":       [],
    "Abdul-Malik":   ["houthi", "israel_yemen"],
    "Starlink":      ["elon_musk_trump"],
    "Nazi":          [],
    "Hitler":        [],
    "SDP":           ["japan_election"],
    "Sisi":          ["gaza_israel", "gaza_usa"],
    "Air Force One": [],
    "BRICS":         [],
    "Iron Dome":     ["gaza_israel", "hamas_israel"],
    "LDP":           ["japan_election"],
    "Portugal":      [],
    "Khotin":        ["russia_ukraine"],
    "Tehran":        ["iran_israel", "iran_usa", "iran_trump"],
    "Hormuz":        ["iran_usa", "iran_israel"],
    "DOGE":          ["elon_musk_trump"],
    "Congo":         [],
    "Azerbaijan":    ["armenia_trump"],
    "Guyana":        [],
    "Epstein":       [],
    "Indus":         ["india_pakistan"],
    "Water":         [],
    "Treaty":        [],
    "Submarine":     [],
    "EDL":           [],
    "UN Human Rights Council": [],
    "CPJ":           [],
    "Mineral":       [],
    "New Zealand":   [],
    "Mahmoud Abbas": ["gaza_israel", "hamas_israel"],
    "Toretsk":       ["russia_ukraine"],
    "Tel Aviv":      ["gaza_israel", "hamas_israel"],
    "Ontario":       [],
    "Gavin Newsom":  [],
    "Bagram":        [],
    "Somalia":       [],
    "Öcalan":        ["trump_turkey"],
    "Cory Booker":   [],
    "Hakeem Jeffries": [],
    "Hemedti":       [],
    "Bolivia":       [],
    "Durov":         [],
    "HIMARS":        ["russia_ukraine"],
    "Chad":          [],
    "Republika Srpska": [],
    "Kilmar Abrego Garcia": [],
    "Ben Gvir":      ["hamas_israel", "gaza_israel"],
    "National Security": [],
    "HTS":           ["syria"],
    "Grok":          ["elon_musk_trump"],
    "Cyberattack":   [],
    "Belgium":       [],
    "Kyiv":          ["russia_ukraine", "moscow_ukraine"],
    "Serbia":        [],
    "Kharg":         ["iran_israel", "iran_usa"],
    "Washington":    [],
    "DC":            [],
    "America":       ["iran_usa", "gaza_usa", "saudi_arabia_usa", "usa_venezuela"],
    "American":      ["iran_usa", "gaza_usa", "saudi_arabia_usa"],
    "Nuke":          ["iran_israel", "iran_usa", "north_korea"],
    "ICC":           [],
    "DEI":           [],
    "Persian Gulf":  ["gulf_trump", "saudi_arabia_usa"],
    "Oil":           ["iran_usa", "iran_israel"],
    "xAI":           ["elon_musk_trump"],
    "Nepal":         [],
    "Kurd":          ["trump_turkey"],
    "Kurdish":       ["trump_turkey"],
    "Chasiv Yar":    ["russia_ukraine"],
    "Baghdad":       ["iraq_israel"],
    "Nvidia":        [],
    "Ireland":       [],
    "Norway":        [],
    "Obama":         [],
    "Greece":        [],
    "Sudan":         [],
    "Kazakhstan":    [],
    "Korea":         ["south_korea_trump", "yoon", "north_korea"],
    "Trudeau":       [],
    "Kurakhove":     ["russia_ukraine"],
    "PKK":           ["trump_turkey"],
    "Heathrow":      [],
    "Netherlands":   [],
    "Abraham Accord": ["israel_saudi"],
    "SpaceX":        ["elon_musk_trump"],
    "Sánchez":        ["spain_sanchez"],
    "Guterres":      ["trump_un_general_assembly"],
    "LNG":           ["iran_usa", "russia_ukraine"],
    "WHO":           [],
    "G7":            [],
    "WTO":           [],
    "Donetsk":       ["russia_ukraine"],
    "Semiconductor": ["china_taiwan"],
    "Kenya":         [],
    "Gold":          [],
    "Ishiba":        ["japan_election", "south_korea_trump"],
    "Vietnam":       [],
    "Palau":         ["china_taiwan"],
    "Paraguay":      [],
    "Colombia":      [],
    "South Africa":  ["south_african_trump"],
    "Philadelphi":   ["gaza_israel", "hamas_israel"],
    "Warsaw Pact":   [],
    "Mykolaivka":    ["russia_ukraine"],
    "Julian Assange": [],
    "ICC":           [],
    "BRICS":         [],
    "Wagner":        ["russia_ukraine", "russia_syria"],
    "Zaporizhzhia":  ["russia_ukraine"],
    "Kharkiv":       ["russia_ukraine"],
    "Mariupol":      ["russia_ukraine"],
    "Kharg":         ["iran_israel", "iran_usa"],
    "Orbán":         ["orban"],

}



# 5. KEYWORD_TO_TICKERS

# maps NER keyword → relevant stock/ETF tickers
# keys match canonical display form from KNOWN_NAMES (same as KEYWORD_TO_CORPORA)
# ordered by frequency from inspect_keywords.py output
# empty list [] = no liquid instrument to map to
#
# ticker notes:
#   LMT/RTX/NOC/GD  = US defence primes (move on conflict escalation)
#   USO             = US Oil Fund ETF (crude oil proxy)
#   XOM/CVX         = major US oil majors
#   SHEL/BP         = European energy (Russia/gas exposure)
#   WEAT/CORN       = grain futures ETFs (Ukraine = major exporter)
#   GLD             = gold (geopolitical risk hedge, spikes on escalation)
#   TLT             = 20yr US treasury ETF (rate/macro risk)
#   SPY             = S&P 500 (broad macro)
#   DXY             = US dollar index
#   TSM             = TSMC (Taiwan strait risk proxy)
#   NVDA            = Nvidia (AI + China export controls)
#   EWG/EWQ/EWU     = Germany/France/UK country ETFs
#   FEZ             = Euro Stoxx 50 ETF
#   EWZ             = Brazil ETF
#   INDA            = India ETF
#   TUR             = Turkey ETF
#   EPOL            = Poland ETF
#   005930.KS       = Samsung (South Korea political risk)
#   000660.KS       = SK Hynix (South Korea political risk)
#   CNH=X           = Chinese yuan (trade war proxy)
#   GBP=X           = British pound
#   EUR=X           = Euro
#   BTC-USD         = Bitcoin
#   ETH-USD         = Ethereum
 
KEYWORD_TO_TICKERS = {

    # Israel / Palestine 
    "Israel":        ["LMT", "RTX", "NOC", "GD", "GLD"],
    "Trump":         ["DXY", "GLD", "TLT", "SPY"],
    "Iran":          ["USO", "XOM", "CVX", "GLD"],
    "USA":           ["DXY", "SPY", "TLT"],
    "Russia":        ["USO", "SHEL", "BP", "WEAT", "GLD"],
    "Zelenskyy":     ["WEAT", "LMT", "RTX", "GLD"],
    "Ukraine":       ["WEAT", "CORN", "LMT", "RTX"],
    "Yemen":         ["USO", "XOM", "LMT", "RTX"],
    "Putin":         ["USO", "SHEL", "WEAT", "GLD"],
    "Gaza":          ["LMT", "RTX", "NOC", "GLD"],
    "Netanyahu":     ["LMT", "RTX", "GLD"],
    "Syria":         ["USO", "LMT", "GLD"],
    "Hamas":         ["LMT", "RTX", "GLD"],
    "South Korea":   ["005930.KS", "000660.KS", "LMT"],
    "India":         ["INDA", "LMT", "GLD"],
    "NATO":          ["LMT", "RTX", "NOC", "GD"],
    "UN General Assembly": ["GLD", "TLT"],
    "Pakistan":      ["LMT", "GLD"],
    "Starmer":       ["EWU", "GBP=X"],
    "Turkey":        ["TUR", "GLD"],
    "Elon Musk":     ["TSLA", "NVDA"],
    "North Korea":   ["LMT", "RTX", "005930.KS", "GLD"],
    "Japan":         [],
    "Saudi Arabia":  ["USO", "XOM", "CVX"],
    "China":         ["TSM", "NVDA", "USDCNH=X"],
    "Pope":          [],
    "Houthi":        ["USO", "LMT", "RTX"],
    "Merz":          ["EWG", "FEZ"],
    "House of Councillors": [],
    "Poland":        ["EPOL", "LMT"],
    "Xi Jinping":    ["TSM", "CNH=X", "NVDA"],
    "UK":            ["EWU", "GBP=X"],
    "Macron":        ["EWQ", "FEZ", "EUR=X"],
    "Bitcoin":       ["BTC-USD"],
    "Yoon":          ["005930.KS", "000660.KS"],
    "Lebanon":       ["LMT", "RTX", "GLD"],
    "Crypto":        ["BTC-USD", "ETH-USD"],
    "UN":            ["GLD", "TLT"],
    "EU":            ["FEZ", "EUR=X"],
    "Gulf Leaders Summit": ["USO", "XOM"],
    "Vance":         ["GLD", "TLT"],
    "Rutte":         ["LMT", "RTX", "FEZ"],
    "NATO Public Forum Address": ["LMT", "RTX"],
    "Palestine":     ["LMT", "RTX", "GLD"],
    "South African": ["GLD"],
    "Khamenei":      ["USO", "GLD"],
    "Armenia":       ["GLD"],
    "Al-Sharaa":     ["USO", "GLD"],
    "Pokrovsk":      ["WEAT", "LMT"],
    "Qatar":         ["USO", "LMT"],
    "AI":            ["NVDA", "MSFT", "GOOGL", "AMD"],
    "France":        ["EWQ", "FEZ", "EUR=X"],
    "Hezbollah":     ["LMT", "RTX", "GLD"],
    "Kim Jong Un":   ["LMT", "RTX", "GLD"],
    "Venezuela":     ["USO"],
    "Canada":        [],
    "Moscow":        ["WEAT", "USO", "SHEL"],
    "Germany":       ["EWG", "FEZ", "EUR=X"],
    "Lula":          ["EWZ"],
    "MBS":           ["USO", "XOM"],
    "Crimea":        ["WEAT", "LMT", "GLD"],
    "Brazil":        ["EWZ"],
    "Bolsonaro":     ["EWZ"],
    "Egypt":         ["GLD"],
    "Greta Thunberg": [],
    "Constitutional Court": ["005930.KS", "000660.KS"],
    "Siversk":       ["WEAT"],
    "Biden":         [],
    "Erdoğan":       ["TUR", "GLD"],
    "Iraq":          ["USO", "LMT"],
    "Baier":         [],
    "Maduro":        ["USO"],
    "Damascus":      ["USO", "LMT"],
    "Taiwan":        ["TSM", "NVDA"],
    "Sudzha":        ["WEAT"],
    "Kupiansk":      ["WEAT"],
    "Yunakivka":     ["WEAT"],
    "Thailand":      [],
    "Jerome Powell": ["TLT", "DXY", "SPY"],
    "Assad":         ["USO", "GLD"],
    "Rodynske":      ["WEAT"],
    "Donbas":        ["WEAT", "LMT"],
    "Milei":         [],
    "Belarus":       ["GLD"],
    "Switzerland":   [],
    "Mexico":        ["MXN=X"],
    "Apple":         ["AAPL"],
    "Fordow":        ["USO", "GLD"],
    "Australia":     [],
    "Argentina":     [],
    "Novopavlivka":  ["WEAT"],
    "Von der Leyen": ["FEZ", "EUR=X"],
    "TikTok":        ["META", "GOOGL"],
    "Dnipropetrovsk": ["WEAT"],
    "Beirut Embassy": ["LMT", "RTX", "GLD"],
    "Meloni":        ["FEZ", "EUR=X"],
    "Cambodia":      [],
    "Dobropillia":   ["WEAT"],
    "Jordan":        ["GLD", "LMT"],
    "MrBeast":       [],
    "Greenland":     [],
    "Italy":         ["FEZ", "EUR=X"],
    "UAE":           ["USO"],
    "Saudi-US":      ["USO", "XOM"],
    "Congress":      ["DXY", "TLT"],
    "Nord Stream":   ["SHEL", "BP"],
    "Afghanistan":   ["LMT", "GLD"],
    "Nasrallah":     ["LMT", "RTX", "GLD"],
    "Alaska":        [],
    "Carney":        ["EWC", "CAD=X"],
    "Udachne":       ["WEAT"],
    "Pope Francis":  [],
    "Lukashenko":    ["GLD"],
    "Hungary":       ["FEZ"],
    "Ceasefire":     ["GLD", "LMT"],
    "Spain":         ["FEZ", "EUR=X"],
    "Modi":          ["INDA", "LMT"],
    "Dimonah":       ["USO", "GLD"],
    "JCP":           [],
    "Reiwa Shinsengumi": [],
    "Suez Canal":    ["USO", "XOM"],
    "Tesla":         ["TSLA"],
    "Reza Pahlavi":  ["USO", "GLD"],
    "Austria":       [],
    "Vatican":       [],
    "Sinwar":        ["LMT", "RTX"],
    "Panama":        ["USO"],
    "Black Sea":     ["WEAT", "USO"],
    "Machado":       ["USO"],
    "Witkoff":       ["GLD"],
    "West Bank":     ["LMT", "RTX", "GLD"],
    "Indonesia":     [],
    "Stepanivka":    ["WEAT"],
    "UNRWA":         ["GLD"],
    "DeepSeek":      ["NVDA", "AMD"],
    "Lai Ching-te":  ["TSM"],
    "NPT":           ["GLD", "USO"],
    "Gulf State":    ["USO", "XOM"],
    "White House":   ["DXY", "GLD"],
    "IDF":           ["LMT", "RTX"],
    "CDP":           [],
    "Suwayda":       ["USO", "GLD"],
    "Marco Rubio":   ["GLD", "TLT"],
    "Beirut":        ["LMT", "RTX", "GLD"],
    "Telegram":      [],
    "Iran Nuke":     ["USO", "GLD"],
    "Philippines":   [],
    "JIP":           [],
    "Komeito":       [],
    "DPP":           ["TSM"],
    "Mintsuku":      [],
    "Finland":       [],
    "Abdul-Malik":   ["USO", "LMT"],
    "Starlink":      ["TSLA"],
    "Nazi":          [],
    "Hitler":        [],
    "SDP":           [],
    "Sisi":          ["GLD"],
    "Air Force One": [],
    "BRICS":         ["GLD", "EEM"],
    "Iron Dome":     ["LMT", "RTX"],
    "LDP":           [],
    "Portugal":      [],
    "Khotin":        ["WEAT"],
    "Tehran":        ["USO", "GLD"],
    "Hormuz":        ["USO", "XOM"],
    "DOGE":          ["TSLA"],
    "Congo":         ["CPER"],
    "Azerbaijan":    ["GLD"],
    "Guyana":        ["USO"],
    "Epstein":       [],
    "Indus":         ["GLD"],
    "Mahmoud Abbas": ["GLD", "LMT"],
    "Toretsk":       ["WEAT"],
    "Tel Aviv":      ["LMT", "RTX", "GLD"],
    "Öcalan":        ["TUR"],
    "HIMARS":        ["LMT", "RTX"],
    "Ben Gvir":      ["LMT", "RTX"],
    "HTS":           ["USO", "GLD"],
    "Grok":          ["TSLA"],
    "Kyiv":          ["WEAT", "LMT"],
    "Kharg":         ["USO"],
    "America":       ["DXY", "SPY", "TLT"],
    "American":      ["DXY", "SPY"],
    "Nuke":          ["GLD", "USO"],
    "Persian Gulf":  ["USO", "XOM"],
    "Oil":           ["USO", "XOM", "CVX"],
    "xAI":           ["TSLA"],
    "PKK":           ["TUR"],
    "Chasiv Yar":    ["WEAT"],
    "Baghdad":       ["USO", "LMT"],
    "Nvidia":        ["NVDA"],
    "Korea":         ["005930.KS", "000660.KS", "LMT"],
    "Trudeau":       [],
    "Kurakhove":     ["WEAT"],
    "Heathrow":      [],
    "Netherlands":   [],
    "Abraham Accord": ["LMT", "USO"],
    "SpaceX":        ["TSLA"],
    "Sánchez":       ["FEZ", "EUR=X"],
    "Guterres":      [],
    "LNG":           ["SHEL", "BP"],
    "WHO":           [],
    "G7":            ["DXY", "GLD"],
    "WTO":           ["DXY"],
    "Donetsk":       ["WEAT"],
    "Semiconductor": ["NVDA", "TSM", "AMD"],
    "Gold":          ["GLD"],
    "Ishiba":        [],
    "Vietnam":       [],
    "Palau":         ["TSM"],
    "Colombia":      [],
    "South Africa":  ["GLD"],
    "Philadelphi":   ["LMT", "RTX", "GLD"],
    "Warsaw Pact":   ["LMT", "RTX"],
    "Mykolaivka":    ["WEAT"],
    "ICC":           [],
    "Wagner":        ["USO", "GLD"],
    "Zaporizhzhia":  ["WEAT", "LMT"],
    "Kharkiv":       ["WEAT"],
    "Mariupol":      ["WEAT"],
    "Durov":         [],
    "Norway":        [],
    "Ireland":       [],
    "Belgium":       [],
    "Serbia":        [],
    "Greece":        [],
    "Obama":         [],
    "Orbán":         ["FEZ"],

    # Single market / noise 
    "Hemedti":       [],
    "Bolivia":       [],
    "Chad":          [],
    "Republika Srpska": [],
    "Baier":         [],
    "MrBeast":       [],
    "Zangezur Corridor": ["GLD"],
    "Kilmar Abrego Garcia": [],
    "Julian Assange": [],
}